name: Quality Checks

on:
  push:
    branches:
      - '*'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Autoformat with ruff
        run: |
          ruff format src/
          nbqa "ruff format" notebooks/
        continue-on-error: true

      - name: Run linting with ruff
        run: |
          ruff check src/
          nbqa "ruff check --fix" notebooks/
        continue-on-error: true

      - name: Run interrogate
        run: |  
          interrogate -c pyproject.toml
        continue-on-error: true

      - name: Run pytest
        run: |
          python -m pytest -W error
        continue-on-error: true